
module.exports = {
    name: 'commands',
    description: 'I need help with this stupid bot',
    execute(message, args){
        message.channel.send('Commands for @StirringBot918');
        message.channel.send('READ RULES command: !rules');
        message.channel.send('joke');
        message.channel.send('emotional');
        message.channel.send('ping');
        message.channel.send('isubbedtoyouryt');
        message.channel.send('aboutbot');
        message.channel.send('imthedis');
        message.channel.send('iwantstirring');
        message.channel.send('commands');
        message.channel.send('iluvu');
        message.channel.send('NEVER USE THIS COMMAND FOR FUN ONLY USE IT FOR ANNOUNEMENTS command: pinger');
        message.channel.send('kill@a');
        message.channel.send('kill');
        message.channel.send('bit');
        message.channel.send('gamemode1');
        message.channel.send('windows10');
        message.channel.send('windows7');
        message.channel.send('chromebook');
        message.channel.send('gamemode0');
        message.channel.send('ihateu');
        message.channel.send('glass');
        message.channel.send('iwantpeace');
        message.channel.send('respawn');
        message.channel.send('respawn@a');
        message.channel.send('unglass');
        message.channel.send('powershell');
        message.channel.send('cmd');
        message.channel.send('turt');
        message.channel.send('turtle');
        message.channel.send('discordbotlist');
        message.channel.send('emoji');
        message.channel.send('changelog');
        message.channel.send('whichprogramdouusetocode');
        message.channel.send('whichlangdoucodein');
        message.channel.send('confirmmode1');
        message.channel.send('swear');
        message.channel.send('changeprefix.');
        message.channel.send('changeprefix?');
        message.channel.send('changeprefix!');
        message.channel.send('changeprefix=');
        message.channel.send('use/commands');
        message.channel.send('howareudoing');
        message.channel.send('suck');
        message.channel.send('lazy');
        message.channel.send('abc');
        message.channel.send('ep');
        message.channel.send('ogi');
        message.channel.send('pineapple');
        message.channel.send('embed');
        message.channel.send('clock');
        message.channel.send('secret');
        message.channel.send('amongusairshipmap');
        message.channel.send('confirmmode2');
        message.channel.send('confirmmode0');
        message.channel.send('confirmmode3');
        message.channel.send('FREEMCALTSNOVIRUS');
        message.channel.send('pig');
        message.channel.send('icky');
        message.channel.send('srck');
        message.channel.send('0');
        message.channel.send('forget');
        message.channel.send('shutup');
        message.channel.send('tommyinnit');
        message.channel.send('minecraft');
        message.channel.send('discordbotlist');
        message.channel.send('confirmhardcore');
        message.channel.send('hardcore');
        message.channel.send('ilikesponge');
        message.channel.send('ihatesponge');
        message.channel.send('canihavedankstirringplz');
        message.channel.send('gamemode2');
        message.channel.send('gamemode3');
        message.channel.send('gottago');
        message.channel.send('bonjour');
        message.channel.send('canihavedankstirring');
        message.channel.send('chugjugwithme');
        message.channel.send('areyouhuman');
        message.channel.send('ilikeroblox');
        message.channel.send('kickme');
        message.channel.send('COMMANDS DO NOT HAVE SPACES OR CAPITALIZATION');
        message.channel.send('Change the prefixes if you want to the default prefix is: !');
    }
}
